services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6386:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  discovery:
    build: ./app
    environment:
      ROLE: discovery
      SERVICE_NAME: discovery
      SERVICE_HOST: discovery
      SERVICE_PORT: 8500
    command: python /app/app.py
    ports:
      - "8560:8500"

  order:
    build: ./app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      discovery:
        condition: service_started
    environment:
      ROLE: order
      SERVICE_NAME: order
      SERVICE_HOST: order
      SERVICE_PORT: 8081
      DISCOVERY_URL: http://discovery:8500
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://app:app@postgres:5432/app
      BACKPRESSURE_LIMIT: 100
    command: python /app/app.py
    ports:
      - "8061:8081"

  payment:
    build: ./app
    depends_on:
      discovery:
        condition: service_started
    environment:
      ROLE: payment
      SERVICE_NAME: payment
      SERVICE_HOST: payment
      SERVICE_PORT: 8082
      DISCOVERY_URL: http://discovery:8500
      PAYMENT_FAILURE_RATE: 0.30
    command: python /app/app.py
    ports:
      - "8062:8082"

  gateway:
    build: ./app
    depends_on:
      discovery:
        condition: service_started
      order:
        condition: service_started
    environment:
      ROLE: gateway
      SERVICE_NAME: gateway
      SERVICE_HOST: gateway
      SERVICE_PORT: 8080
      DISCOVERY_URL: http://discovery:8500
    command: python /app/app.py
    ports:
      - "8060:8080"

  worker:
    build: ./app
    depends_on:
      order:
        condition: service_started
      payment:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ROLE: worker
      SERVICE_NAME: worker
      SERVICE_HOST: worker
      DISCOVERY_URL: http://discovery:8500
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://app:app@postgres:5432/app
    command: python /app/app.py

  notifier:
    build: ./app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ROLE: notifier
      REDIS_URL: redis://redis:6379/0
    command: python /app/app.py
