services:
  shard1-primary:
    image: bitnami/postgresql:latest
    container_name: lab4-shard1-primary
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      POSTGRESQL_USERNAME: wallet
      POSTGRESQL_PASSWORD: wallet
      POSTGRESQL_DATABASE: walletdb
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "5441:5432"
    volumes:
      - shard1_primary_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet -d walletdb -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  shard1-replica:
    image: bitnami/postgresql:latest
    container_name: lab4-shard1-replica
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      POSTGRESQL_USERNAME: wallet
      POSTGRESQL_PASSWORD: wallet
      POSTGRESQL_DATABASE: walletdb
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: shard1-primary
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "5442:5432"
    depends_on:
      shard1-primary:
        condition: service_healthy
    volumes:
      - shard1_replica_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet -d walletdb -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  shard2-primary:
    image: bitnami/postgresql:latest
    container_name: lab4-shard2-primary
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      POSTGRESQL_USERNAME: wallet
      POSTGRESQL_PASSWORD: wallet
      POSTGRESQL_DATABASE: walletdb
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "5443:5432"
    volumes:
      - shard2_primary_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet -d walletdb -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  shard2-replica:
    image: bitnami/postgresql:latest
    container_name: lab4-shard2-replica
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      POSTGRESQL_USERNAME: wallet
      POSTGRESQL_PASSWORD: wallet
      POSTGRESQL_DATABASE: walletdb
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: shard2-primary
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "5444:5432"
    depends_on:
      shard2-primary:
        condition: service_healthy
    volumes:
      - shard2_replica_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet -d walletdb -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: ./app
    container_name: lab4-app
    depends_on:
      shard1-primary:
        condition: service_healthy
      shard1-replica:
        condition: service_healthy
      shard2-primary:
        condition: service_healthy
      shard2-replica:
        condition: service_healthy
    environment:
      DB_USER: wallet
      DB_PASSWORD: wallet
      DB_NAME: walletdb
      SHARD1_PRIMARY_HOST: shard1-primary
      SHARD1_REPLICA_HOST: shard1-replica
      SHARD2_PRIMARY_HOST: shard2-primary
      SHARD2_REPLICA_HOST: shard2-replica
      DB_PORT: "5432"

volumes:
  shard1_primary_data:
  shard1_replica_data:
  shard2_primary_data:
  shard2_replica_data:
